### ISSUE TITLE
Error: `The latest segment's sample timestamp is greater than max_int64 for timestamp(-1)`

### ISSUE THREAD

**Issue by d-uzlov** [deckhouse/prompp#28]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/prompp/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/prompp/issues) for an issue that matches the one I want to file, without success.

### Version

2.53.2-0.1.5

### Expected Behavior

prompp is a drop in replacement for vanilla prometheus, and it works without issues.

### Actual Behavior

When I set up prompp with the same config as my current prometheus, it quickly gets the `The latest segment's sample timestamp (1743217894462) is greater than max_int64 for timestamp(-1)` error.

It seems like at first scraping works OK, but then some unexpected input or some race condition happens, and prompp transitions to a bad state, at which point every next scrape fails.

Interesting side effect is that history recording stops, prompp quickly starts eating the CPU, stabilizing at ~3 cores, and starts steadily consuming more and more memory (I guess that's because WAL head block fails to write to disk, so it is never released from memory).

### Steps To Reproduce

I've been running prompp for 4+ hours without issues until I added large targets, but as soon as there is enough targets it stops working.

I tried reproducing it with smaller config, and found out that I can reliably reproduce it with just kubelet cadvisor scraping.
But I'm really not sure if it is related at all. Maybe the issue is just because cadvisor is producing a lot of metrics, unlike all of my other scrape targets. When looking at prompp container logs from previous deployments, I see that in different runs the first error appeared after different scrapes.

Here is how I can reproduce the issue using cadvisor scrape:

1. Deploy cadvisor scrape config (I copied my config fully, in case it would matter):

<details>
<summary>Open me</summary>

```yaml
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kubelet-cadvisor
  namespace: prometheus
  labels:
    prometheus.io/instance: main
spec:
  kubernetesSDConfigs:
  - role: Node
  scheme: HTTPS
  metricsPath: /metrics/cadvisor
  tlsConfig:
    ca:
      configMap:
        name: kube-root-ca.crt
        key: ca.crt
  authorization:
    credentials:
      name: prometheus-sa-token
      key: token
  honorLabels: true
  honorTimestamps: true
  trackTimestampsStaleness: true
  relabelings:
  - targetLabel: job
    replacement: kubelet-cadvisor
  - targetLabel: cluster_type
    replacement: k8s
  - targetLabel: node
    sourceLabels: [ instance ]
  metricRelabelings:
  # drop metrics for dummy cgroup containers without name
  - sourceLabels:
    - __name__
    - container
    action: drop
    # select only metrics that are linked to containers
    # for example, network metrics do not have container label by design
    regex: 'container_(cpu_|fs_|blkio_|memory_|oom_|start_time_|threads|processes|sockets|ulimits_soft).*;'
    separator: ;
  - sourceLabels:
    - __name__
    - interface
    action: drop
    # drop lxc* interface metrics
    # they are kinda impossible to correlate with k8s objects
    # they don't seem to have any real traffic reported
    # but they give huge cardinality for pods with hostNetwork enabled
    regex: 'container_network_.*;lxc.*'
    separator: ;
  # iops metrics don't seems to be useful ?
  # - sourceLabels: [__name__]
  #   action: drop
  #   regex: 'container_fs_reads_total|container_fs_writes_total'
  # Drop less useful container CPU metrics.
  - sourceLabels: [__name__]
    action: drop
    regex: 'container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)'
  # Drop less useful container / always zero filesystem metrics.
  - sourceLabels: [__name__]
    action: drop
    regex: 'container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)'
  # Drop less useful / always zero container memory metrics.
  - sourceLabels: [__name__]
    action: drop
    # regex: 'container_memory_swap|container_memory_kernel_usage|container_memory_mapped_file'
    regex: 'container_memory_swap|container_memory_kernel_usage'
  # Drop less useful container process metrics.
  - sourceLabels: [__name__]
    action: drop
    regex: 'container_(file_descriptors|tasks_state|threads_max)'
  # Drop container spec metrics that overlap with kube-state-metrics.
  - sourceLabels: [__name__]
    action: drop
    regex: 'container_spec.*'
  # Drop cgroup metrics with no pod.
  - sourceLabels: [id, pod]
    action: drop
    regex: '.+;'
  - sourceLabels: [__name__]
    action: drop
    regex: container_last_seen
  - sourceLabels: [ __name__, scope ]
    action: drop
    # container_memory_failures_total{scope="container"} == container_memory_failures_total{scope="hierarchy"}
    regex: container_memory_failures_total;hierarchy
    separator: ;
```

</details>

2. Deploy Prometheus with prompp via prometheus-operator:

<details>
<summary>Open me</summary>

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prompp
  namespace: prometheus
  labels:
    app: prompp
spec:
  version: v2.53.2
  replicas: 1
  logLevel:  debug
  logFormat:  logfmt
  enableAdminAPI: true
  scrapeInterval: 10s
  evaluationInterval: 10s
  retention: 10y
  securityContext:
    fsGroup: 64535
    runAsGroup: 64535
    runAsNonRoot: true
    runAsUser: 64535
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus.io/instance: prompp
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      prometheus.io/instance: prompp
  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      prometheus.io/instance: prompp
  probeNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus.io/instance: prompp
  ruleNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      instance.prometheus.io/prompp: enable3
  scrapeConfigNamespaceSelector: {}
  image: prompp/prompp:2.53.2-0.1.5
  imagePullPolicy: Always
  initContainers:
  - name: prompptool
    image: prompp/prompp:2.53.2-0.1.5
    imagePullPolicy: Always
    command:
      - /bin/prompptool
      - "--working-dir=/prometheus"
      - "walvanilla"
    volumeMounts:
    - name: db
      mountPath: /prometheus
      subPath: prometheus-db
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
```

</details>

3. Enable monitoring for the cadvisor scrape config:

```bash
kubectl -n prometheus label scrapeconfigs.monitoring.coreos.com --overwrite kubelet-cadvisor instance.prometheus.io/prompp=enable3
```

4. Check logs for a message like this: `"wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225032220) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225032220) is greater than max_int64 for timestamp(-1)"`

### Additional Information

k8s apiserver version: `v1.32.1`
prometheus-operator version: `v0.81.0`
prompp docker image: `prompp/prompp:2.53.2-0.1.5`
prompp docker image hash: `docker.io/prompp/prompp@sha256:a8f19e9ba023095cc87f17ef50ae20cefbf61b8cae3ffde52409af57051cf646`

Logs from the run described in "Steps To Reproduce":
[prompp-3-kubelet-cadvisor.log](https://github.com/user-attachments/files/19515878/prompp-3-kubelet-cadvisor.log)

### Logs

```shell
ts=2025-03-29T05:10:31.075Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=serviceMonitor/prometheus/prompp/1 target=http://10.201.2.137:8080/metrics msg="scrape append" total=179 stats="unsupported value type"
ts=2025-03-29T05:10:31.640Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.1.0:10250/metrics/cadvisor msg="scrape append" total=3415 stats="unsupported value type"
ts=2025-03-29T05:10:31.769Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.1.1:10250/metrics/cadvisor msg="scrape append" total=2997 stats="unsupported value type"
ts=2025-03-29T05:10:32.432Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.0:10250/metrics/cadvisor msg="scrape append" total=9872 stats="unsupported value type"
ts=2025-03-29T05:10:33.574Z caller=receiver.go:776 level=error component=receiver op_caller=rotator.go:89 msg="wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225032220) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225032220) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:35.529Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.12:10250/metrics/cadvisor msg="scrape append" total=3105 stats="unsupported value type"
ts=2025-03-29T05:10:35.531Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=serviceMonitor/prometheus/prompp/0 target=http://10.201.2.137:9090/metrics msg="scrape append" total=630 stats="unsupported value type"
ts=2025-03-29T05:10:37.399Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.3:10250/metrics/cadvisor msg="scrape append" total=15094 stats="unsupported value type"
ts=2025-03-29T05:10:38.575Z caller=receiver.go:776 level=error component=receiver op_caller=rotator.go:89 msg="wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225037037) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225037037) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:41.073Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=serviceMonitor/prometheus/prompp/1 target=http://10.201.2.137:8080/metrics msg="scrape append" total=179 stats="unsupported value type"
ts=2025-03-29T05:10:41.618Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.1.0:10250/metrics/cadvisor msg="scrape append" total=3415 stats="unsupported value type"
ts=2025-03-29T05:10:41.755Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.1.1:10250/metrics/cadvisor msg="scrape append" total=2997 stats="unsupported value type"
ts=2025-03-29T05:10:42.396Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.0:10250/metrics/cadvisor msg="scrape append" total=9872 stats="unsupported value type"
ts=2025-03-29T05:10:43.576Z caller=receiver.go:776 level=error component=receiver op_caller=rotator.go:89 msg="wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225042220) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225042220) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:45.511Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.12:10250/metrics/cadvisor msg="scrape append" total=3105 stats="unsupported value type"
ts=2025-03-29T05:10:45.518Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=serviceMonitor/prometheus/prompp/0 target=http://10.201.2.137:9090/metrics msg="scrape append" total=691 stats="unsupported value type"
ts=2025-03-29T05:10:47.309Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.3:10250/metrics/cadvisor msg="scrape append" total=15106 stats="unsupported value type"
ts=2025-03-29T05:10:48.577Z caller=receiver.go:776 level=error component=receiver op_caller=rotator.go:89 msg="wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225047037) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225047037) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:51.072Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=serviceMonitor/prometheus/prompp/1 target=http://10.201.2.137:8080/metrics msg="scrape append" total=179 stats="unsupported value type"
ts=2025-03-29T05:10:51.627Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.1.0:10250/metrics/cadvisor msg="scrape append" total=3415 stats="unsupported value type"
ts=2025-03-29T05:10:51.758Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.1.1:10250/metrics/cadvisor msg="scrape append" total=2997 stats="unsupported value type"
ts=2025-03-29T05:10:52.418Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.0:10250/metrics/cadvisor msg="scrape append" total=9872 stats="unsupported value type"
ts=2025-03-29T05:10:53.578Z caller=receiver.go:776 level=error component=receiver op_caller=rotator.go:89 msg="wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225052220) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225052220) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:55.509Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.12:10250/metrics/cadvisor msg="scrape append" total=3105 stats="unsupported value type"
ts=2025-03-29T05:10:55.517Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=serviceMonitor/prometheus/prompp/0 target=http://10.201.2.137:9090/metrics msg="scrape append" total=691 stats="unsupported value type"
ts=2025-03-29T05:10:57.331Z caller=receiver.go:776 level=error component=receiver op_caller=head.go:337 msg="failed to commit wal: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225057005) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225057005) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:57.331Z caller=scrape.go:1001 level=debug component="scrape manager" scrape_pool=scrapeConfig/prometheus/kubelet-cadvisor target=https://10.3.10.3:10250/metrics/cadvisor msg="scrape append" total=15106 stats="unsupported value type"
ts=2025-03-29T05:10:57.331Z caller=receiver.go:776 level=error component=receiver op_caller=head.go:337 msg="failed to commit wal: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225057037) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225057037) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:10:58.579Z caller=receiver.go:776 level=error component=receiver op_caller=rotator.go:89 msg="wal commit failed: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225057037) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225057037) is greater than max_int64 for timestamp(-1)"
ts=2025-03-29T05:11:01.070Z caller=receiver.go:776 level=error component=receiver op_caller=head.go:337 msg="failed to commit wal: failed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225061067) is greater than max_int64 for timestamp(-1)\nfailed to finalize segment: opcore_head_wal_encoder_finalize(): Exception 546e143d302c4860: The latest segment's sample timestamp (1743225061067) is greater than max_int64 for timestamp(-1)"
```
