### ISSUE TITLE
Publish container image to GHCR or Quay

### ISSUE THREAD

**Issue by onedr0p** [deckhouse/prompp#94]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/prompp/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/prompp/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Hi 👋 

Dockerhub has aggressive rate limits for unauthorized pulls (100/ 6 hours) and for authorized pulls (200/ 6 hours) and also actively prunes inactive tags.

### Proposed Solution

Please publish your image to a more open source friendly container registry like GHCR or Quay

### Additional Information

I am not asking to remove the image from Dockerhub, only to publish it to an additional registry that doesn't have such asinine pull limits.

**Comment by vladimirGuryanov** [comment]
Hi 👋

Thanks for the suggestion!

Starting from version 2.53.2-0.2.3, we also publish images to our own registry: `registry.deckhouse.io/prompp/`

You can pull the image with:
```

docker pull registry.deckhouse.io/prompp/prompp:2.53.2-0.2.3
```

Let us know if GHCR or Quay support would still be helpful — we're open to adding more mirrors if needed.

**Comment by onedr0p** [comment]
That's good to know but I think GHCR would still be useful and it integrates into your GitHub repository too under the packages.

**Comment by vladimirGuryanov** [comment]
We’ll add this to our backlog and consider it. Before moving forward, we’ll need to review GHCR’s limitations — as far as we know, there are some — and also coordinate with other product teams to align on a common solution across all our projects.

**Comment by onedr0p** [comment]
As far as I'm aware there are no limitations with GHCR for open source projects, and if there are it's not as bad as DockerHub 😄

**Comment by rjshrjndrn** [comment]
Seems like the container is not drop in replaceable for kube prometheus stack. I had to create custom image.
```
FROM alpine:3.19 AS builder

# Download and extract prompp binary
RUN apk add --no-cache wget=1.21.4-r0 && \
  wget -q -O /tmp/prompp-binaries.tar.gz https://github.com/deckhouse/prompp/releases/download/v2.53.2-0.2.6/prompp-binaries-arm64.tar.gz && \
  tar -xzf /tmp/prompp-binaries.tar.gz -C /tmp

FROM quay.io/prometheus/prometheus:v2.54.1

# Copy prompp binary from builder stage with specific ownership
COPY --from=builder --chown=1000:2000 /tmp/prompp /bin/prometheus
```

**Comment by onedr0p** [comment]
@rjshrjndrn as the README suggests you need to update the security context like this:

```yaml
      prometheusSpec:
        image:
          registry: docker.io
          repository: prompp/prompp
          tag: 2.53.2-0.2.5
        securityContext:
          runAsNonRoot: true
          runAsUser: 64535
          runAsGroup: 64535
          fsGroup: 64535
```

**Comment by rjshrjndrn** [comment]
My bad 😅. Didn't read fully. Sure, I'll give it a try. Thanks.

Jun 24, 2025 14:36:32 Devin Buhl ***@***.***>:

**Comment by onedr0p** [comment]
FYI on newer prompp versions you need to also set the version field...

```yaml
prometheusSpec:
  version: v2.55.1 # bypass 'unsupported Prometheus version' error
  image:
    registry: docker.io
    repository: prompp/prompp
    tag: 0.5.1
  securityContext:
    runAsNonRoot: true
    runAsUser: 64535
    runAsGroup: 64535
    fsGroup: 64535
```
